version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgresdb
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    secrets:
      - postgres_password

  pgadmin:
    image: dpage/pgadmin4:latest  
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "82:80"
    networks:
      - postgres-network
    depends_on:
      - postgres

networks:
  postgres-network:
    driver: bridge

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
